services:
  web:
    build: .
    container_name: cocktail_web
    command: gunicorn drink_recipes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8003:8000"  # Exposing on Port 8003
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: cocktail_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cocktail_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
  static_volume:
  media_volume: